function Hd = iir_120hz
%IIR_120HZ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
% Generated on: 02-Nov-2022 18:05:07

% Chebyshev Type II Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
Fs = 360;  % Sampling Frequency

Fpass1 = 110;         % First Passband Frequency
Fstop1 = 115;         % First Stopband Frequency
Fstop2 = 125;         % Second Stopband Frequency
Fpass2 = 130;         % Second Passband Frequency
Apass1 = 0.5;         % First Passband Ripple (dB)
Astop  = 60;          % Stopband Attenuation (dB)
Apass2 = 1;           % Second Passband Ripple (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandstop(Fpass1, Fstop1, Fstop2, Fpass2, Apass1, Astop, ...
                      Apass2, Fs);
Hd = design(h, 'cheby2', 'MatchExactly', match);

[b,a]=sos2tf(Hd.sosMatrix, Hd.ScaleValues);

fileID = fopen("a_coef_120.bin", 'wb');
fwrite(fileID, a, 'double');
fclose(fileID);

fileID = fopen("b_coef_120.bin", 'wb');
fwrite(fileID, b, 'double');
fclose(fileID);

freqz(b, a, 'whole', 360);

z = Hd.sosMatrix;

% [EOF]
